<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using docker with stevedore • stevedore</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">stevedore</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/stevedore.html">Get Started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/examples.html">Examples and use-cases</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Using docker with stevedore</h1>
                        <h4 class="author">Rich FitzJohn</h4>
            
            <h4 class="date">2018-04-16</h4>
          </div>

    
    
<div class="contents">
<p><code>stevedore</code> is an R package for interacting with docker from R. With <code>stevedore</code> you can</p>
<ul>
<li>create, run, manage, remove and destroy containers</li>
<li>build, pull, manage and remove images</li>
<li>create, destroy and interact with docker networks</li>
<li>create, destroy and interact with docker volumes</li>
</ul>
<p>Almost everything that can be done with the docker command line client (the main exception being that is not possible to send input to a container as if you were on a terminal).</p>
<p><code>stevedore</code> directly interacts with the docker server over its HTTP API. This gives a more direct access to docker than going via the command line.</p>
<p>This vignette quickly walks through the core features of the package. Because <code>stevedore</code> wraps the docker API directly there are many more arguments that can be used than are covered here. But this covers the core use.</p>
<p>The main function in the package is <code>docker_client</code>; this will construct an object with which we can talk with the docker server. Currently this is hardcoded to only work with a docker server that is running over the default unix socket (<code>/var/run/docker.sock</code>), but hopefully soon this can be relaxed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker &lt;-<span class="st"> </span>stevedore::<span class="kw"><a href="../reference/docker_client.html">docker_client</a></span>()</code></pre></div>
<p>The client object looks a lot like an <a href="https://github.com/wch/R6"><code>R6</code></a> object (though it is implemented differently because the interface here is automatically generated in ways that don’t play nicely with R6). But if you are at all familiar with R6 objects it should seem quite familiar.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker</code></pre></div>
<pre><code>## &lt;docker_client&gt;
##   config: Manage docker swarm configs
##   container: Work with docker containers
##   image: Work with docker images
##   network: Work with docker networks
##   node: Manage docker swarm nodes
##   plugin: Work with docker plugins
##   secret: Manage docker swarm secrets
##   service: Work with docker services
##   swarm: Manage the docker swarm
##   task: Work with docker tasks
##   volume: Work with docker volumes
##   types: Methods for building complex docker types
##   api_version()
##   df()
##   events(since = NULL, until = NULL, filters = NULL)
##   help(help_type = getOption("help_type"))
##   info()
##   login(username = NULL, password = NULL, email = NULL,
##       serveraddress = NULL)
##   ping()
##   version()</code></pre>
<p>Each function call (e.g., <code>ping</code>) is callable by accessing with <code>$</code>, such as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$<span class="kw">ping</span>()</code></pre></div>
<pre><code>## [1] "OK"
## attr(,"api_version")
## [1] "1.37"
## attr(,"docker_experimental")
## [1] TRUE</code></pre>
<p>In addition there are “collection” objects (e.g., <code>container</code>) that are accessed using <code>$</code>, like a directory structure</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container</code></pre></div>
<pre><code>## &lt;docker_container_collection&gt;
##   create(image, cmd = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL,
##       health_check = NULL, args_escaped = NULL, volumes = NULL,
##       working_dir = NULL, entrypoint = NULL, network_disabled = NULL,
##       mac_address = NULL, on_build = NULL, labels = NULL,
##       stop_signal = NULL, stop_timeout = NULL, shell = NULL,
##       host_config = NULL, network = NULL, name = NULL)
##   get(id)
##   help(help_type = getOption("help_type"))
##   list(all = NULL, limit = NULL, size = NULL, filters = NULL)
##   prune(filters = NULL)
##   remove(id, delete_volumes = NULL, force = NULL, link = NULL)
##   run(image, cmd = NULL, ..., detach = FALSE, rm = FALSE,
##       stream = stdout(), host_config = NULL)</code></pre>
<p>The interface is designed similarly to the command line docker client (and to the Python docker client), where container commands are within the <code>container</code> collection and image commands are within the <code>image</code> collection and so on (the main difference with the command line client is that the container commands are not at the top level, so it is <code>docker$container$run(...)</code> not <code>docker$run(...)</code>).</p>
<p>To run a container, the <code>docker$container$run</code> command follows the semantics of the command line client and will</p>
<ul>
<li>pull a image if it does not exist</li>
<li>create the container</li>
<li>run the container</li>
<li>fetch the logs</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res &lt;-<span class="st"> </span>docker$container$<span class="kw">run</span>(<span class="st">"hello-world"</span>)</code></pre></div>
<pre><code>## O&gt;
## O&gt; Hello from Docker!
## O&gt; This message shows that your installation appears to be working correctly.
## O&gt;
## O&gt; To generate this message, Docker took the following steps:
## O&gt;  1. The Docker client contacted the Docker daemon.
## O&gt;  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
## O&gt;     (amd64)
## O&gt;  3. The Docker daemon created a new container from that image which runs the
## O&gt;     executable that produces the output you are currently reading.
## O&gt;  4. The Docker daemon streamed that output to the Docker client, which sent it
## O&gt;     to your terminal.
## O&gt;
## O&gt; To try something more ambitious, you can run an Ubuntu container with:
## O&gt;  $ docker run -it ubuntu bash
## O&gt;
## O&gt; Share images, automate workflows, and more with a free Docker ID:
## O&gt;  https://hub.docker.com/
## O&gt;
## O&gt; For more examples and ideas, visit:
## O&gt;  https://docs.docker.com/engine/userguide/
## O&gt;</code></pre>
<p>This returns a list with two elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(res)</code></pre></div>
<pre><code>## [1] "container" "logs"</code></pre>
<p>The “logs” element is the logs themselves:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res$logs</code></pre></div>
<pre><code>## O&gt;
## O&gt; Hello from Docker!
## O&gt; This message shows that your installation appears to be working correctly.
## O&gt;
## O&gt; To generate this message, Docker took the following steps:
## O&gt;  1. The Docker client contacted the Docker daemon.
## O&gt;  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
## O&gt;     (amd64)
## O&gt;  3. The Docker daemon created a new container from that image which runs the
## O&gt;     executable that produces the output you are currently reading.
## O&gt;  4. The Docker daemon streamed that output to the Docker client, which sent it
## O&gt;     to your terminal.
## O&gt;
## O&gt; To try something more ambitious, you can run an Ubuntu container with:
## O&gt;  $ docker run -it ubuntu bash
## O&gt;
## O&gt; Share images, automate workflows, and more with a free Docker ID:
## O&gt;  https://hub.docker.com/
## O&gt;
## O&gt; For more examples and ideas, visit:
## O&gt;  https://docs.docker.com/engine/userguide/
## O&gt;</code></pre>
<p>This is a <code>docker_stream</code> object and codes the output stream using the <code>stream</code> attribute (it can otherwise be treated as a character vector).</p>
<p>The “container” element is an object that can be used to interact with a container</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res$container</code></pre></div>
<pre><code>## &lt;docker_container&gt;
##   commit(repo = NULL, tag = NULL, author = NULL, changes = NULL,
##       comment = NULL, pause = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, exposed_ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL, cmd = NULL,
##       healthcheck = NULL, args_escaped = NULL, image = NULL,
##       volumes = NULL, working_dir = NULL, entrypoint = NULL,
##       network_disabled = NULL, mac_address = NULL, on_build = NULL,
##       labels = NULL, stop_signal = NULL, stop_timeout = NULL,
##       shell = NULL)
##   diff()
##   exec(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL)
##   export()
##   get_archive(path, dest)
##   help(help_type = getOption("help_type"))
##   id()
##   image()
##   inspect(reload = TRUE)
##   kill(signal = NULL)
##   labels(reload = TRUE)
##   logs(follow = NULL, stdout = TRUE, stderr = TRUE, since = NULL,
##       timestamps = NULL, tail = NULL, stream = stdout())
##   name()
##   path_stat(path)
##   pause()
##   ports(reload = TRUE)
##   put_archive(src, path, no_overwrite_dir_non_dir = NULL)
##   reload()
##   remove(delete_volumes = NULL, force = NULL, link = NULL)
##   rename(name)
##   resize(h = NULL, w = NULL)
##   restart(t = NULL)
##   start(detach_keys = NULL)
##   stats()
##   status(reload = TRUE)
##   stop(t = NULL)
##   top(ps_args = NULL)
##   unpause()
##   update(cpu_shares = NULL, memory = NULL, cgroup_parent = NULL,
##       blkio_weight = NULL, blkio_weight_device = NULL,
##       blkio_device_read_bps = NULL, blkio_device_write_bps = NULL,
##       blkio_device_read_iops = NULL, blkio_device_write_iops = NULL,
##       cpu_period = NULL, cpu_quota = NULL, cpu_realtime_period = NULL,
##       cpu_realtime_runtime = NULL, cpuset_cpus = NULL,
##       cpuset_mems = NULL, devices = NULL, device_cgroup_rules = NULL,
##       disk_quota = NULL, kernel_memory = NULL,
##       memory_reservation = NULL, memory_swap = NULL,
##       memory_swappiness = NULL, nano_cpus = NULL,
##       oom_kill_disable = NULL, pids_limit = NULL, ulimits = NULL,
##       cpu_count = NULL, cpu_percent = NULL, io_maximum_iops = NULL,
##       io_maximum_bandwidth = NULL, restart_policy = NULL)
##   wait()</code></pre>
<p>For example the function <code>path_stat</code> gets some information about paths on the container:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res$container$<span class="kw">path_stat</span>(<span class="st">"hello"</span>)</code></pre></div>
<pre><code>## $name
## [1] "hello"
##
## $size
## [1] 1848
##
## $mode
## [1] 509
##
## $mtime
## [1] "2018-04-11T18:11:31Z"
##
## $linkTarget
## [1] ""</code></pre>
<p>The image can also be returned</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img &lt;-<span class="st"> </span>res$container$<span class="kw">image</span>()
img</code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>which is another object with methods that can be invoked to find out about the image, e.g.:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">history</span>()</code></pre></div>
<pre><code>##                                                                        id
## 1 sha256:e38bc07ac18ee64e6d59cf2eafcdddf9cec2364dfe129fe0af75f1b0194e0c96
## 2                                                               &lt;missing&gt;
##      created
## 1 1523470309
## 2 1523470309
##                                                                                           created_by
## 1                                                                  /bin/sh -c #(nop)  CMD ["/hello"]
## 2 /bin/sh -c #(nop) COPY file:3c3ca82dfdb40d30f91a91e2ee953fc0193dc455289fe87fd85219a2c19edcea in /
##           tags size comment
## 1 hello-wo....    0
## 2              1848</code></pre>
<div id="containers" class="section level2">
<h2 class="hasAnchor">
<a href="#containers" class="anchor"></a>Containers</h2>
<p>The <code>$container</code> object includes methods for interacting with containers:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container</code></pre></div>
<pre><code>## &lt;docker_container_collection&gt;
##   create(image, cmd = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL,
##       health_check = NULL, args_escaped = NULL, volumes = NULL,
##       working_dir = NULL, entrypoint = NULL, network_disabled = NULL,
##       mac_address = NULL, on_build = NULL, labels = NULL,
##       stop_signal = NULL, stop_timeout = NULL, shell = NULL,
##       host_config = NULL, network = NULL, name = NULL)
##   get(id)
##   help(help_type = getOption("help_type"))
##   list(all = NULL, limit = NULL, size = NULL, filters = NULL)
##   prune(filters = NULL)
##   remove(id, delete_volumes = NULL, force = NULL, link = NULL)
##   run(image, cmd = NULL, ..., detach = FALSE, rm = FALSE,
##       stream = stdout(), host_config = NULL)</code></pre>
<p><code>$create</code> creates a new container (similar to <code>docker container create</code> on the command line) but does not start it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>docker$container$<span class="kw">create</span>(<span class="st">"hello-world"</span>, <span class="dt">name =</span> <span class="st">"hello-stevedore"</span>)
x</code></pre></div>
<pre><code>## &lt;docker_container&gt;
##   commit(repo = NULL, tag = NULL, author = NULL, changes = NULL,
##       comment = NULL, pause = NULL, hostname = NULL, domainname = NULL,
##       user = NULL, attach_stdin = NULL, attach_stdout = NULL,
##       attach_stderr = NULL, exposed_ports = NULL, tty = NULL,
##       open_stdin = NULL, stdin_once = NULL, env = NULL, cmd = NULL,
##       healthcheck = NULL, args_escaped = NULL, image = NULL,
##       volumes = NULL, working_dir = NULL, entrypoint = NULL,
##       network_disabled = NULL, mac_address = NULL, on_build = NULL,
##       labels = NULL, stop_signal = NULL, stop_timeout = NULL,
##       shell = NULL)
##   diff()
##   exec(cmd, stdin = NULL, stdout = TRUE, stderr = TRUE,
##       detach_keys = NULL, tty = NULL, env = NULL, privileged = NULL,
##       user = NULL)
##   export()
##   get_archive(path, dest)
##   help(help_type = getOption("help_type"))
##   id()
##   image()
##   inspect(reload = TRUE)
##   kill(signal = NULL)
##   labels(reload = TRUE)
##   logs(follow = NULL, stdout = TRUE, stderr = TRUE, since = NULL,
##       timestamps = NULL, tail = NULL, stream = stdout())
##   name()
##   path_stat(path)
##   pause()
##   ports(reload = TRUE)
##   put_archive(src, path, no_overwrite_dir_non_dir = NULL)
##   reload()
##   remove(delete_volumes = NULL, force = NULL, link = NULL)
##   rename(name)
##   resize(h = NULL, w = NULL)
##   restart(t = NULL)
##   start(detach_keys = NULL)
##   stats()
##   status(reload = TRUE)
##   stop(t = NULL)
##   top(ps_args = NULL)
##   unpause()
##   update(cpu_shares = NULL, memory = NULL, cgroup_parent = NULL,
##       blkio_weight = NULL, blkio_weight_device = NULL,
##       blkio_device_read_bps = NULL, blkio_device_write_bps = NULL,
##       blkio_device_read_iops = NULL, blkio_device_write_iops = NULL,
##       cpu_period = NULL, cpu_quota = NULL, cpu_realtime_period = NULL,
##       cpu_realtime_runtime = NULL, cpuset_cpus = NULL,
##       cpuset_mems = NULL, devices = NULL, device_cgroup_rules = NULL,
##       disk_quota = NULL, kernel_memory = NULL,
##       memory_reservation = NULL, memory_swap = NULL,
##       memory_swappiness = NULL, nano_cpus = NULL,
##       oom_kill_disable = NULL, pids_limit = NULL, ulimits = NULL,
##       cpu_count = NULL, cpu_percent = NULL, io_maximum_iops = NULL,
##       io_maximum_bandwidth = NULL, restart_policy = NULL)
##   wait()</code></pre>
<p><code>$get</code> creates a <code>docker_container</code> object from an container id or name:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>docker$container$<span class="kw">get</span>(<span class="st">"hello-stevedore"</span>)
x$<span class="kw">id</span>()</code></pre></div>
<pre><code>## [1] "18b05e101d69c42fe0e9a8345bfaa2e868b3abc027345655e9d4a8ad5eae242c"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y$<span class="kw">id</span>()</code></pre></div>
<pre><code>## [1] "18b05e101d69c42fe0e9a8345bfaa2e868b3abc027345655e9d4a8ad5eae242c"</code></pre>
<p><code>$list()</code> lists containers (like <code>docker list</code> on the command line) - by default showing only running containers</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">list</span>()</code></pre></div>
<pre><code>##  [1] id               names            image            image_id
##  [5] command          created          ports            size_rw
##  [9] size_root_fs     labels           state            status
## [13] host_config      network_settings mounts           name
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">list</span>(<span class="dt">all =</span> <span class="ot">TRUE</span>, <span class="dt">limit =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>##                                                                 id
## 1 18b05e101d69c42fe0e9a8345bfaa2e868b3abc027345655e9d4a8ad5eae242c
## 2 a5092487e191a7fb66c1b822dea44ccaf12ca29e13a50d9252527e68cb71d408
##          names
## 1 hello-st....
## 2 inspirin....
##                                                                     image
## 1                                                             hello-world
## 2 sha256:e38bc07ac18ee64e6d59cf2eafcdddf9cec2364dfe129fe0af75f1b0194e0c96
##                                                                  image_id
## 1 sha256:e38bc07ac18ee64e6d59cf2eafcdddf9cec2364dfe129fe0af75f1b0194e0c96
## 2 sha256:e38bc07ac18ee64e6d59cf2eafcdddf9cec2364dfe129fe0af75f1b0194e0c96
##   command    created        ports size_rw size_root_fs labels   state
## 1  /hello 1523909242 characte....      NA           NA        created
## 2  /hello 1523909241 characte....      NA           NA         exited
##                    status host_config network_settings       mounts
## 1                 Created     default     list(bri.... characte....
## 2 Exited (0) 1 second ago     default     list(bri.... characte....
##                  name
## 1     hello-stevedore
## 2 inspiring_blackwell</code></pre>
<p><code>$remove()</code> removes a container by name or id:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">remove</span>(<span class="st">"hello-stevedore"</span>)</code></pre></div>
<pre><code>## NULL</code></pre>
<p><code>$prune()</code> removes non-running containers (i.e., containers that have exited or containers that have been created but not yet started)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">prune</span>()</code></pre></div>
<pre><code>## $containers_deleted
## [1] "a5092487e191a7fb66c1b822dea44ccaf12ca29e13a50d9252527e68cb71d408"
## [2] "6ed546e54baa8e8c469e7262f6f0fdbb127a79fc0c572dc09b52f57f311605c0"
##
## $space_reclaimed
## [1] 0</code></pre>
<div id="working-with-containers" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-containers" class="anchor"></a>Working with containers</h3>
<p>After creating a container object, there are many more methods to use - all apply to the individual container</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>docker$container$<span class="kw">create</span>(<span class="st">"richfitz/iterate"</span>, <span class="kw">c</span>(<span class="st">"1000"</span>, <span class="st">"1"</span>))</code></pre></div>
<p>Most are analogues of similarly named <code>docker</code> command line functions.</p>
<p>First, there are some basic query methods - <code>$id()</code>, <code>$name()</code> and <code>$labels()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">id</span>()</code></pre></div>
<pre><code>## [1] "da6c95dba4aedc7e9789846ab30198fbcfb162386947d520257bda21e5cce9d2"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">name</span>()</code></pre></div>
<pre><code>## [1] "pensive_johnson"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">labels</span>()</code></pre></div>
<pre><code>## stevedore_version
##           "0.0.1"</code></pre>
<p>More detailed information (<strong>much</strong> more detailed) can be reteieved with the <code>$inspect()</code> method</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">inspect</span>()</code></pre></div>
<pre><code>## $id
## [1] "da6c95dba4aedc7e9789846ab30198fbcfb162386947d520257bda21e5cce9d2"
##
## $created
## [1] "2018-04-16T20:07:23.2055035Z"
##
## $path
## [1] "/usr/local/bin/iterate"
##
## $args
## [1] "1000" "1"
##
## $state
## $state$status
## [1] "created"
##
## $state$running
## [1] FALSE
##
## $state$paused
## [1] FALSE
##
## $state$restarting
## [1] FALSE
##
## $state$oom_killed
## [1] FALSE
##
## $state$dead
## [1] FALSE
##
## $state$pid
## [1] 0
##
## $state$exit_code
## [1] 0
##
## $state$error
## [1] ""
##
## $state$started_at
## [1] "0001-01-01T00:00:00Z"
##
## $state$finished_at
## [1] "0001-01-01T00:00:00Z"
##
##
## $image
## [1] "sha256:50f3ab513c06ee645398374b9b3624d49273868519d29524d709b6715d38ad7a"
##
## $resolv_conf_path
## [1] ""
##
## $hostname_path
## [1] ""
##
## $hosts_path
## [1] ""
##
## $log_path
## [1] ""
##
## $node
## NULL
##
## $name
## [1] "/pensive_johnson"
##
## $restart_count
## [1] 0
##
## $driver
## [1] "overlay2"
##
## $mount_label
## [1] ""
##
## $process_label
## [1] ""
##
## $app_armor_profile
## [1] ""
##
## $exec_ids
## [1] NA
##
## $host_config
## $host_config$cpu_shares
## [1] 0
##
## $host_config$memory
## [1] 0
##
## $host_config$cgroup_parent
## [1] ""
##
## $host_config$blkio_weight
## [1] 0
##
## $host_config$blkio_weight_device
## [1] path   weight
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_read_bps
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_write_bps
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_read_iops
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$blkio_device_write_iops
## [1] path rate
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cpu_period
## [1] 0
##
## $host_config$cpu_quota
## [1] 0
##
## $host_config$cpu_realtime_period
## [1] 0
##
## $host_config$cpu_realtime_runtime
## [1] 0
##
## $host_config$cpuset_cpus
## [1] ""
##
## $host_config$cpuset_mems
## [1] ""
##
## $host_config$devices
## [1] path_on_host       path_in_container  cgroup_permissions
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$device_cgroup_rules
## character(0)
##
## $host_config$disk_quota
## [1] 0
##
## $host_config$kernel_memory
## [1] 0
##
## $host_config$memory_reservation
## [1] 0
##
## $host_config$memory_swap
## [1] 0
##
## $host_config$memory_swappiness
## [1] NA
##
## $host_config$nano_cpus
## [1] NA
##
## $host_config$oom_kill_disable
## [1] FALSE
##
## $host_config$pids_limit
## [1] 0
##
## $host_config$ulimits
## [1] name soft hard
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cpu_count
## [1] 0
##
## $host_config$cpu_percent
## [1] 0
##
## $host_config$io_maximum_iops
## [1] 0
##
## $host_config$io_maximum_bandwidth
## [1] 0
##
## $host_config$binds
## character(0)
##
## $host_config$container_idfile
## [1] ""
##
## $host_config$log_config
## $host_config$log_config$type
## [1] "json-file"
##
## $host_config$log_config$config
## character(0)
##
##
## $host_config$network_mode
## [1] "default"
##
## $host_config$port_bindings
## NULL
##
## $host_config$restart_policy
## $host_config$restart_policy$name
## [1] ""
##
## $host_config$restart_policy$maximum_retry_count
## [1] 0
##
##
## $host_config$auto_remove
## [1] FALSE
##
## $host_config$volume_driver
## [1] ""
##
## $host_config$volumes_from
## character(0)
##
## $host_config$mounts
## [1] target         source         type           read_only
## [5] consistency    bind_options   volume_options tmpfs_options
## &lt;0 rows&gt; (or 0-length row.names)
##
## $host_config$cap_add
## character(0)
##
## $host_config$cap_drop
## character(0)
##
## $host_config$dns
## character(0)
##
## $host_config$dns_options
## character(0)
##
## $host_config$dns_search
## character(0)
##
## $host_config$extra_hosts
## character(0)
##
## $host_config$group_add
## character(0)
##
## $host_config$ipc_mode
## [1] "shareable"
##
## $host_config$cgroup
## [1] ""
##
## $host_config$links
## character(0)
##
## $host_config$oom_score_adj
## [1] 0
##
## $host_config$pid_mode
## [1] ""
##
## $host_config$privileged
## [1] FALSE
##
## $host_config$publish_all_ports
## [1] FALSE
##
## $host_config$readonly_rootfs
## [1] FALSE
##
## $host_config$security_opt
## character(0)
##
## $host_config$storage_opt
## NULL
##
## $host_config$tmpfs
## NULL
##
## $host_config$uts_mode
## [1] ""
##
## $host_config$userns_mode
## [1] ""
##
## $host_config$shm_size
## [1] 67108864
##
## $host_config$sysctls
## NULL
##
## $host_config$runtime
## [1] NA
##
## $host_config$console_size
## [1] 0 0
##
## $host_config$isolation
## [1] ""
##
##
## $graph_driver
## $graph_driver$name
## [1] "overlay2"
##
## $graph_driver$data
##                                                                                                                                                                                                                                                                                           lower_dir
## "/var/lib/docker/overlay2/67bf0b07cd5a047e3824eae17f5dfcdccf0d4ea9b747fa98e9e1c59c91fd6cd0-init/diff:/var/lib/docker/overlay2/7e094570d98a9db0192c4b486230d480bd4607e3302ba3b3f1add765a1a41652/diff:/var/lib/docker/overlay2/a5ef0a95e9164f9b6f05e0a961f1f2e7e9167020ed3cb3eabab66e4349c5704d/diff"
##                                                                                                                                                                                                                                                                                          merged_dir
##                                                                                                                                                                                                  "/var/lib/docker/overlay2/67bf0b07cd5a047e3824eae17f5dfcdccf0d4ea9b747fa98e9e1c59c91fd6cd0/merged"
##                                                                                                                                                                                                                                                                                           upper_dir
##                                                                                                                                                                                                    "/var/lib/docker/overlay2/67bf0b07cd5a047e3824eae17f5dfcdccf0d4ea9b747fa98e9e1c59c91fd6cd0/diff"
##                                                                                                                                                                                                                                                                                            work_dir
##                                                                                                                                                                                                    "/var/lib/docker/overlay2/67bf0b07cd5a047e3824eae17f5dfcdccf0d4ea9b747fa98e9e1c59c91fd6cd0/work"
##
##
## $size_rw
## [1] NA
##
## $size_root_fs
## [1] NA
##
## $mounts
## [1] type        name        source      destination driver      mode
## [7] rw          propagation
## &lt;0 rows&gt; (or 0-length row.names)
##
## $config
## $config$hostname
## [1] "da6c95dba4ae"
##
## $config$domainname
## [1] ""
##
## $config$user
## [1] ""
##
## $config$attach_stdin
## [1] FALSE
##
## $config$attach_stdout
## [1] FALSE
##
## $config$attach_stderr
## [1] FALSE
##
## $config$exposed_ports
## NULL
##
## $config$tty
## [1] FALSE
##
## $config$open_stdin
## [1] FALSE
##
## $config$stdin_once
## [1] FALSE
##
## $config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $config$cmd
## [1] "1000" "1"
##
## $config$healthcheck
## NULL
##
## $config$args_escaped
## [1] NA
##
## $config$image
## [1] "richfitz/iterate"
##
## $config$volumes
## NULL
##
## $config$working_dir
## [1] ""
##
## $config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $config$network_disabled
## [1] NA
##
## $config$mac_address
## [1] NA
##
## $config$on_build
## character(0)
##
## $config$labels
## stevedore_version
##           "0.0.1"
##
## $config$stop_signal
## [1] NA
##
## $config$stop_timeout
## [1] NA
##
## $config$shell
## character(0)
##
##
## $network_settings
## $network_settings$bridge
## [1] ""
##
## $network_settings$gateway
## [1] ""
##
## $network_settings$address
## [1] NA
##
## $network_settings$ip_prefix_len
## [1] 0
##
## $network_settings$mac_address
## [1] ""
##
## $network_settings$port_mapping
## [1] NA
##
## $network_settings$ports
## list()</code></pre>
<p>The image used by a container can be retrieved with the <code>$image()</code> method</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">image</span>()</code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>(see below for working with images).</p>
<p>The status of the container (<code>created</code>, <code>running</code>, <code>exited</code>, <code>paused</code>, etc) can be read with <code>$status()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "created"</code></pre>
<p>The container created by by <code>$create</code> is not running - the <code>$start()</code> method will start it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">start</span>()
x$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Once the container is running we can query to see what processes are running in it with <code>$top</code> (standing for Table Of Processes)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">top</span>()</code></pre></div>
<pre><code>##     PID USER TIME                                         COMMAND
## 1 29465 root 0:00 {iterate} /bin/sh /usr/local/bin/iterate 1000 1
## 2 29492 root 0:00                                         sleep 1</code></pre>
<p>We can also get the logs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">logs</span>()</code></pre></div>
<pre><code>## O&gt; Doing 1000 iterations with interval 1
## O&gt; Iteration 1...</code></pre>
<p>This returns a special object type <code>docker_stream</code> which allows control over formatting with <code>format()</code> - the <code>style</code> argument controls how stderr and stdout are printed. There is a <code>stream</code> attribute that can be used to separate out lines too. If a tty was allocated with <code>tty = TRUE</code> the output will be a plain character vector</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">format</span>(x$<span class="kw">logs</span>(), <span class="dt">style =</span> <span class="st">"plain"</span>)</code></pre></div>
<pre><code>## [1] "Doing 1000 iterations with interval 1\n"
## [2] "Iteration 1...\n"</code></pre>
<p>It can generally be treated as a character vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">logs</span>()[<span class="dv">1</span>:<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] "Doing 1000 iterations with interval 1\n"
## [2] "Iteration 1...\n"</code></pre>
<p>The <code>$logs()</code> method can be used to do a blocking wait on a container. Pass <code>follow = TRUE</code> to follow the logs. You will want to provide a <code>stream</code> argument too, which is where to stream the log to. This can be <code>stdout()</code> or <code>stderr()</code>, a file or an R connection.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>docker$container$<span class="kw">create</span>(<span class="st">"richfitz/iterate"</span>, <span class="kw">c</span>(<span class="st">"10"</span>, <span class="st">"0.1"</span>))
y$<span class="kw">start</span>()
y$<span class="kw">logs</span>(<span class="dt">stream =</span> <span class="kw">stdout</span>(), <span class="dt">follow =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## O&gt; Doing 10 iterations with interval 0.1
## O&gt; Iteration 1...
## O&gt; Iteration 2...
## O&gt; Iteration 3...
## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Iteration 6...
## O&gt; Iteration 7...
## O&gt; Iteration 8...
## O&gt; Iteration 9...
## O&gt; Iteration 10...
## O&gt; Done!</code></pre>
<p>If running this interactively, the logs will print one line at a time - once control returns to R the container has exited. You can escape this streaming using whatever method you use to interrupt an R calculation (depends on which GUI/IDE you are using) but the container will continue regardless - we are just <em>observing</em> a running container.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "exited"</code></pre>
<p>The other way of blocking until a container has finished is with <code>$wait()</code> which blocks until the container exits, then returns the exit code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y$<span class="kw">start</span>()
y$<span class="kw">wait</span>()</code></pre></div>
<pre><code>## $status_code
## [1] 0</code></pre>
<p>Calling <code>$wait()</code> on an exited container is fine, and will just return immediately:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y$<span class="kw">wait</span>()</code></pre></div>
<pre><code>## $status_code
## [1] 0</code></pre>
<p>Containers can be paused with <code>$pause()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">pause</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "paused"</code></pre>
<p>Once paused, they can be restarted with <code>$unpause()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">unpause</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Additionally, containers can be <em>restarted</em> with <code>$restart()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">restart</span>(<span class="dt">t =</span> <span class="dv">0</span>)</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">logs</span>(<span class="dt">tail =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## O&gt; Iteration 3...
## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Doing 1000 iterations with interval 1
## O&gt; Iteration 1...</code></pre>
<p>Containers can be stopped with <code>$stop()</code> and removed with <code>$remove()</code> (calling <code>$remove(force = TRUE)</code> will kill the container before removing.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">stop</span>(<span class="dt">t =</span> <span class="dv">0</span>)</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">remove</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<p>Once a container has been removed most methods will not work properly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$<span class="kw">status</span>()</code></pre></div>
<pre><code>## Error: No such container: da6c95dba4aedc7e9789846ab30198fbcfb162386947d520257bda21e5cce9d2</code></pre>
<p>Information about ports (for containers that expose them) can be retrieved with <code>$ports()</code>. The <code>nginx</code> image creates a web server/proxy that exposes port 80 from the container. We can map that to a random port by asking docker to expose port 80 but not saying what to map it to:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nginx &lt;-<span class="st"> </span>docker$container$<span class="kw">run</span>(<span class="st">"nginx"</span>, <span class="dt">ports =</span> <span class="dv">80</span>,
                              <span class="dt">detach =</span> <span class="ot">TRUE</span>, <span class="dt">rm =</span> <span class="ot">TRUE</span>,
                              <span class="dt">name =</span> <span class="st">"stevedore-nginx"</span>)
nginx$<span class="kw">ports</span>()</code></pre></div>
<pre><code>##   container_port protocol host_ip host_port
## 1             80      tcp 0.0.0.0     32776</code></pre>
<p>(alternatively, use <code>ports = TRUE</code> to act like <code>docker run</code>’s <code>-P</code> and “publish all ports to random ports).</p>
<p>This shows that the port exposed by the the container (80) is mapped to the port 32776 on the host. We can use this to communicate with the server:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">url &lt;-<span class="st"> </span><span class="kw">sprintf</span>(<span class="st">"http://localhost:%s"</span>, nginx$<span class="kw">ports</span>()$host_port)
curl::<span class="kw">parse_headers</span>(curl::<span class="kw">curl_fetch_memory</span>(url)$headers)</code></pre></div>
<pre><code>## [1] "HTTP/1.1 200 OK"
## [2] "Server: nginx/1.13.12"
## [3] "Date: Mon, 16 Apr 2018 20:07:30 GMT"
## [4] "Content-Type: text/html"
## [5] "Content-Length: 612"
## [6] "Last-Modified: Mon, 09 Apr 2018 16:01:09 GMT"
## [7] "Connection: keep-alive"
## [8] "ETag: \"5acb8e45-264\""
## [9] "Accept-Ranges: bytes"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nginx$<span class="kw">stop</span>(<span class="dt">t =</span> <span class="dv">0</span>)</code></pre></div>
<pre><code>## NULL</code></pre>
</div>
</div>
<div id="images" class="section level2">
<h2 class="hasAnchor">
<a href="#images" class="anchor"></a>Images</h2>
<div id="pulling" class="section level3">
<h3 class="hasAnchor">
<a href="#pulling" class="anchor"></a>Pulling</h3>
<p>Images can be directly pulled with <code>docker$image$pull</code> providing an image name (as either <code>&lt;repo&gt;</code> or <code>&lt;repo&gt;:&lt;tag&gt;</code>. If the image exists already this will be quick, and if the network connection is down then this will fail.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$image$<span class="kw">pull</span>(<span class="st">"bash:latest"</span>)</code></pre></div>
<pre><code>## Pulling from library/bash latest
## Pulling fs layer 605ce1bd3f31
## Pulling fs layer f691ab0a0436
## Pulling fs layer 3d7d3f4179eb
## 605ce1bd3f31: Downloading 26.52 kB/1.99 MB 1%
## Download complete 3d7d3f4179eb
## 605ce1bd3f31: Downloading 124.82 kB/1.99 MB 6%
## f691ab0a0436: Downloading 36.66 kB/2.71 MB 1%
## f691ab0a0436: Downloading 97.39 kB/2.71 MB 4%
## 605ce1bd3f31: Downloading 190.36 kB/1.99 MB 10%
## f691ab0a0436: Downloading 162.93 kB/2.71 MB 6%
## 605ce1bd3f31: Downloading 255.9 kB/1.99 MB 13%
## f691ab0a0436: Downloading 228.47 kB/2.71 MB 8%
## 605ce1bd3f31: Downloading 321.43 kB/1.99 MB 16%
## f691ab0a0436: Downloading 294 kB/2.71 MB 11%
## f691ab0a0436: Downloading 359.54 kB/2.71 MB 13%
## 605ce1bd3f31: Downloading 386.97 kB/1.99 MB 19%
## f691ab0a0436: Downloading 425.07 kB/2.71 MB 16%
## 605ce1bd3f31: Downloading 452.5 kB/1.99 MB 23%
## f691ab0a0436: Downloading 490.61 kB/2.71 MB 18%
## 605ce1bd3f31: Downloading 518.04 kB/1.99 MB 26%
## f691ab0a0436: Downloading 556.15 kB/2.71 MB 21%
## 605ce1bd3f31: Downloading 583.58 kB/1.99 MB 29%
## f691ab0a0436: Downloading 621.68 kB/2.71 MB 23%
## 605ce1bd3f31: Downloading 649.11 kB/1.99 MB 33%
## f691ab0a0436: Downloading 687.22 kB/2.71 MB 25%
## 605ce1bd3f31: Downloading 714.65 kB/1.99 MB 36%
## f691ab0a0436: Downloading 752.75 kB/2.71 MB 28%
## 605ce1bd3f31: Downloading 780.18 kB/1.99 MB 39%
## 605ce1bd3f31: Downloading 845.72 kB/1.99 MB 42%
## f691ab0a0436: Downloading 818.29 kB/2.71 MB 30%
## 605ce1bd3f31: Downloading 911.26 kB/1.99 MB 46%
## f691ab0a0436: Downloading 883.83 kB/2.71 MB 33%
## 605ce1bd3f31: Downloading 976.79 kB/1.99 MB 49%
## f691ab0a0436: Downloading 949.36 kB/2.71 MB 35%
## 605ce1bd3f31: Downloading 1.04 MB/1.99 MB 52%
## f691ab0a0436: Downloading 1.01 MB/2.71 MB 37%
## 605ce1bd3f31: Downloading 1.11 MB/1.99 MB 56%
## f691ab0a0436: Downloading 1.05 MB/2.71 MB 39%
## 605ce1bd3f31: Downloading 1.14 MB/1.99 MB 57%
## 605ce1bd3f31: Downloading 1.24 MB/1.99 MB 62%
## f691ab0a0436: Downloading 1.11 MB/2.71 MB 41%
## 605ce1bd3f31: Downloading 1.34 MB/1.99 MB 67%
## f691ab0a0436: Downloading 1.18 MB/2.71 MB 43%
## 605ce1bd3f31: Downloading 1.4 MB/1.99 MB 70%
## f691ab0a0436: Downloading 1.24 MB/2.71 MB 46%
## 605ce1bd3f31: Downloading 1.5 MB/1.99 MB 75%
## f691ab0a0436: Downloading 1.28 MB/2.71 MB 47%
## 605ce1bd3f31: Downloading 1.6 MB/1.99 MB 80%
## 605ce1bd3f31: Downloading 1.66 MB/1.99 MB 84%
## f691ab0a0436: Downloading 1.34 MB/2.71 MB 49%
## 605ce1bd3f31: Downloading 1.73 MB/1.99 MB 87%
## f691ab0a0436: Downloading 1.38 MB/2.71 MB 51%
## 605ce1bd3f31: Downloading 1.86 MB/1.99 MB 93%
## f691ab0a0436: Downloading 1.44 MB/2.71 MB 53%
## 605ce1bd3f31: Downloading 1.96 MB/1.99 MB 98%
## 605ce1bd3f31: Downloading 1.99 MB/1.99 MB 100%
## Download complete 605ce1bd3f31
## f691ab0a0436: Downloading 1.51 MB/2.71 MB 56%
## 605ce1bd3f31: Extracting 32.77 kB/1.99 MB 2%
## 605ce1bd3f31: Extracting 753.66 kB/1.99 MB 38%
## 605ce1bd3f31: Extracting 1.99 MB/1.99 MB 100%
## 605ce1bd3f31: Extracting 1.99 MB/1.99 MB 100%
## Pull complete 605ce1bd3f31
## f691ab0a0436: Downloading 1.54 MB/2.71 MB 57%
## f691ab0a0436: Downloading 1.57 MB/2.71 MB 58%
## f691ab0a0436: Downloading 1.6 MB/2.71 MB 59%
## f691ab0a0436: Downloading 1.64 MB/2.71 MB 60%
## f691ab0a0436: Downloading 1.7 MB/2.71 MB 63%
## f691ab0a0436: Downloading 1.74 MB/2.71 MB 64%
## f691ab0a0436: Downloading 1.77 MB/2.71 MB 65%
## f691ab0a0436: Downloading 1.83 MB/2.71 MB 68%
## f691ab0a0436: Downloading 1.87 MB/2.71 MB 69%
## f691ab0a0436: Downloading 1.9 MB/2.71 MB 70%
## f691ab0a0436: Downloading 1.93 MB/2.71 MB 71%
## f691ab0a0436: Downloading 2 MB/2.71 MB 74%
## f691ab0a0436: Downloading 2.03 MB/2.71 MB 75%
## f691ab0a0436: Downloading 2.06 MB/2.71 MB 76%
## f691ab0a0436: Downloading 2.13 MB/2.71 MB 78%
## f691ab0a0436: Downloading 2.16 MB/2.71 MB 80%
## f691ab0a0436: Downloading 2.19 MB/2.71 MB 81%
## f691ab0a0436: Downloading 2.23 MB/2.71 MB 82%
## f691ab0a0436: Downloading 2.26 MB/2.71 MB 83%
## f691ab0a0436: Downloading 2.29 MB/2.71 MB 85%
## f691ab0a0436: Downloading 2.36 MB/2.71 MB 87%
## f691ab0a0436: Downloading 2.39 MB/2.71 MB 88%
## f691ab0a0436: Downloading 2.46 MB/2.71 MB 91%
## f691ab0a0436: Downloading 2.49 MB/2.71 MB 92%
## f691ab0a0436: Downloading 2.55 MB/2.71 MB 94%
## f691ab0a0436: Downloading 2.62 MB/2.71 MB 97%
## f691ab0a0436: Downloading 2.69 MB/2.71 MB 99%
## Verifying Checksum f691ab0a0436
## Download complete f691ab0a0436
## f691ab0a0436: Extracting 32.77 kB/2.71 MB 1%
## f691ab0a0436: Extracting 983.04 kB/2.71 MB 36%
## f691ab0a0436: Extracting 2.59 MB/2.71 MB 95%
## f691ab0a0436: Extracting 2.71 MB/2.71 MB 100%
## Pull complete f691ab0a0436
## 3d7d3f4179eb: Extracting 342 B/342 B 100%
## 3d7d3f4179eb: Extracting 342 B/342 B 100%
## Pull complete 3d7d3f4179eb
## Digest: sha256:717f5f1e5f15624166a6abaa8f5c99a5f812c379f3a5f1a31db1dd7206ef9107
## Status: Downloaded newer image for bash:latest</code></pre>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
</div>
<div id="the-object-returned-by-pull-is-an-image-object---that-can-be" class="section level3">
<h3 class="hasAnchor">
<a href="#the-object-returned-by-pull-is-an-image-object---that-can-be" class="anchor"></a>The object returned by pull is an image object - that can be</h3>
</div>
<div id="created-by-using-get" class="section level3">
<h3 class="hasAnchor">
<a href="#created-by-using-get" class="anchor"></a>created by using <code>$get</code>
</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img &lt;-<span class="st"> </span>docker$image$<span class="kw">get</span>(<span class="st">"bash:latest"</span>)</code></pre></div>
</div>
<div id="building" class="section level3">
<h3 class="hasAnchor">
<a href="#building" class="anchor"></a>Building</h3>
<p>The other common way of getting images is to build them (the equivalent of <code>docker build</code>). So if we have a path (here, <code>iterate</code>) containing a Dockerfile:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir</span>(<span class="st">"iterate"</span>)</code></pre></div>
<pre><code>## [1] "Dockerfile" "iterate"</code></pre>
<p>The Dockerfile itself contains:</p>
<pre class="plain"><code>FROM alpine:latest
COPY iterate /usr/local/bin/iterate
CMD chmod +x /usr/local/bin/iterate
LABEL stevedore_version 0.0.1
ENTRYPOINT ["/usr/local/bin/iterate"]</code></pre>
<p>and the <code>iterate</code> file is an executable shell script containing:</p>
<pre class="shell"><code>#!/bin/sh
set -e

if [ "$#" -ge 1 ]; then
    TIMES=$1
else
    TIMES=10
fi

if [ "$#" -ge 2 ]; then
    INTERVAL=$2
else
    INTERVAL=1
fi

echo "Doing $TIMES iterations with interval $INTERVAL"
i=0
while [ $i -lt $TIMES ]; do
    let i+=1
    echo "Iteration $i..."
    sleep $INTERVAL
done
echo "Done!"</code></pre>
<p>We can build this image using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img &lt;-<span class="st"> </span>docker$image$<span class="kw">build</span>(<span class="st">"iterate"</span>, <span class="dt">tag =</span> <span class="st">"richfitz/iterate"</span>, <span class="dt">nocache =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Step 1/5 : FROM alpine:latest
##  ---&gt; 3fd9065eaf02
## Step 2/5 : COPY iterate /usr/local/bin/iterate
##  ---&gt; e588d8e35a24
## Step 3/5 : CMD chmod +x /usr/local/bin/iterate
##  ---&gt; Running in 5537e9fd8872
## Removing intermediate container 5537e9fd8872
##  ---&gt; 3abc9f53d8d8
## Step 4/5 : LABEL stevedore_version 0.0.1
##  ---&gt; Running in c84487ec27f5
## Removing intermediate container c84487ec27f5
##  ---&gt; cb81cba87b88
## Step 5/5 : ENTRYPOINT ["/usr/local/bin/iterate"]
##  ---&gt; Running in 1ee102a4e1ad
## Removing intermediate container 1ee102a4e1ad
##  ---&gt; 86f15ec2e15f
## Successfully built 86f15ec2e15f
## Successfully tagged richfitz/iterate:latest</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img</code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>The newly created image is returned as an image object and can be used via <code>$container$run()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">invisible</span>(
  docker$container$<span class="kw">run</span>(img, <span class="kw">c</span>(<span class="st">"10"</span>, <span class="st">"0.1"</span>), <span class="dt">rm =</span> <span class="ot">TRUE</span>, <span class="dt">stream =</span> <span class="kw">stdout</span>()))</code></pre></div>
<pre><code>## O&gt; Doing 10 iterations with interval 0.1
## O&gt; Iteration 1...
## O&gt; Iteration 2...
## O&gt; Iteration 3...
## O&gt; Iteration 4...
## O&gt; Iteration 5...
## O&gt; Iteration 6...
## O&gt; Iteration 7...
## O&gt; Iteration 8...
## O&gt; Iteration 9...
## O&gt; Iteration 10...
## O&gt; Done!</code></pre>
</div>
<div id="importing" class="section level3">
<h3 class="hasAnchor">
<a href="#importing" class="anchor"></a>Importing</h3>
<p>There is a third way of creating an image, which is to import it from a tar archive. This is not yet documented (<strong>TODO</strong>) but can be done via <code>$image$import()</code></p>
</div>
<div id="working-with-image-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-image-objects" class="anchor"></a>Working with image objects</h3>
<p>Eachimage object has a number of methods.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img &lt;-<span class="st"> </span>docker$image$<span class="kw">get</span>(<span class="st">"richfitz/iterate"</span>)
img</code></pre></div>
<pre><code>## &lt;docker_image&gt;
##   export()
##   help(help_type = getOption("help_type"))
##   history()
##   id()
##   inspect(reload = TRUE)
##   labels(reload = TRUE)
##   name()
##   reload()
##   remove(force = NULL, noprune = NULL)
##   short_id()
##   tag(repo, tag = NULL)
##   tags(reload = TRUE)
##   untag(repo_tag)</code></pre>
<p>The <code>$id()</code>, <code>$short_id()</code>, <code>$labels()</code>, <code>$name()</code> and <code>$tags()</code> query basic information about an image</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">id</span>()</code></pre></div>
<pre><code>## [1] "sha256:86f15ec2e15f7d505bb013d1b88bf5ba9ec82ed98f29e1bd27f455f957467e67"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">short_id</span>()</code></pre></div>
<pre><code>## [1] "sha256:86f15ec2e1"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">labels</span>()</code></pre></div>
<pre><code>## stevedore_version
##           "0.0.1"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">name</span>()</code></pre></div>
<pre><code>## [1] "richfitz/iterate"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">tags</span>()</code></pre></div>
<pre><code>## [1] "richfitz/iterate:latest"</code></pre>
<p>(short_id<code>is always 10 characters long and does not include a leading</code>sha256:`).</p>
<p>The <code>inspect()</code> method returns detailed information about the image</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">inspect</span>()</code></pre></div>
<pre><code>## $id
## [1] "sha256:86f15ec2e15f7d505bb013d1b88bf5ba9ec82ed98f29e1bd27f455f957467e67"
##
## $repo_tags
## [1] "richfitz/iterate:latest"
##
## $repo_digests
## character(0)
##
## $parent
## [1] "sha256:cb81cba87b88aa00c8acba3588fbe5034e74104c80499de8d329283744d688a6"
##
## $comment
## [1] ""
##
## $created
## [1] "2018-04-16T20:07:44.5452845Z"
##
## $container
## [1] "1ee102a4e1ad0bd204c55d4ac1d5234f0c9ca680b98bc4c50bc108037b295dba"
##
## $container_config
## $container_config$hostname
## [1] "1ee102a4e1ad"
##
## $container_config$domainname
## [1] ""
##
## $container_config$user
## [1] ""
##
## $container_config$attach_stdin
## [1] FALSE
##
## $container_config$attach_stdout
## [1] FALSE
##
## $container_config$attach_stderr
## [1] FALSE
##
## $container_config$exposed_ports
## NULL
##
## $container_config$tty
## [1] FALSE
##
## $container_config$open_stdin
## [1] FALSE
##
## $container_config$stdin_once
## [1] FALSE
##
## $container_config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $container_config$cmd
## [1] "/bin/sh"
## [2] "-c"
## [3] "#(nop) "
## [4] "ENTRYPOINT [\"/usr/local/bin/iterate\"]"
##
## $container_config$healthcheck
## NULL
##
## $container_config$args_escaped
## [1] TRUE
##
## $container_config$image
## [1] "sha256:cb81cba87b88aa00c8acba3588fbe5034e74104c80499de8d329283744d688a6"
##
## $container_config$volumes
## NULL
##
## $container_config$working_dir
## [1] ""
##
## $container_config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $container_config$network_disabled
## [1] NA
##
## $container_config$mac_address
## [1] NA
##
## $container_config$on_build
## character(0)
##
## $container_config$labels
## stevedore_version
##           "0.0.1"
##
## $container_config$stop_signal
## [1] NA
##
## $container_config$stop_timeout
## [1] NA
##
## $container_config$shell
## character(0)
##
##
## $docker_version
## [1] "18.04.0-ce"
##
## $author
## [1] ""
##
## $config
## $config$hostname
## [1] ""
##
## $config$domainname
## [1] ""
##
## $config$user
## [1] ""
##
## $config$attach_stdin
## [1] FALSE
##
## $config$attach_stdout
## [1] FALSE
##
## $config$attach_stderr
## [1] FALSE
##
## $config$exposed_ports
## NULL
##
## $config$tty
## [1] FALSE
##
## $config$open_stdin
## [1] FALSE
##
## $config$stdin_once
## [1] FALSE
##
## $config$env
## [1] "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
##
## $config$cmd
## [1] "/bin/sh"                         "-c"
## [3] "chmod +x /usr/local/bin/iterate"
##
## $config$healthcheck
## NULL
##
## $config$args_escaped
## [1] TRUE
##
## $config$image
## [1] "sha256:cb81cba87b88aa00c8acba3588fbe5034e74104c80499de8d329283744d688a6"
##
## $config$volumes
## NULL
##
## $config$working_dir
## [1] ""
##
## $config$entrypoint
## [1] "/usr/local/bin/iterate"
##
## $config$network_disabled
## [1] NA
##
## $config$mac_address
## [1] NA
##
## $config$on_build
## character(0)
##
## $config$labels
## stevedore_version
##           "0.0.1"
##
## $config$stop_signal
## [1] NA
##
## $config$stop_timeout
## [1] NA
##
## $config$shell
## character(0)
##
##
## $architecture
## [1] "amd64"
##
## $os
## [1] "linux"
##
## $os_version
## [1] NA
##
## $size
## [1] 4148087
##
## $virtual_size
## [1] 4148087
##
## $graph_driver
## $graph_driver$name
## [1] "overlay2"
##
## $graph_driver$data
##                                                                                          lower_dir
##   "/var/lib/docker/overlay2/a5ef0a95e9164f9b6f05e0a961f1f2e7e9167020ed3cb3eabab66e4349c5704d/diff"
##                                                                                         merged_dir
## "/var/lib/docker/overlay2/62820325cc7a03fbe0061b21e614b0b403f59db38844c997482512ea407a4228/merged"
##                                                                                          upper_dir
##   "/var/lib/docker/overlay2/62820325cc7a03fbe0061b21e614b0b403f59db38844c997482512ea407a4228/diff"
##                                                                                           work_dir
##   "/var/lib/docker/overlay2/62820325cc7a03fbe0061b21e614b0b403f59db38844c997482512ea407a4228/work"
##
##
## $root_fs
## $root_fs$type
## [1] "layers"
##
## $root_fs$layers
## [1] "sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215"
## [2] "sha256:f1a81836ef03fd8e5051cb4ca3a26e2cd62a4196f4cad14bfcc05719da5beb16"
##
## $root_fs$base_layer
## [1] NA</code></pre>
<p>the exact format varies between docker API versions but should be the same for all images within an API verison.</p>
<p>The <code>history()</code> method returns a data.frame of information about the history of an image (i.e., the layers that it is constructed from)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">history</span>()</code></pre></div>
<pre><code>##                                                                        id
## 1 sha256:86f15ec2e15f7d505bb013d1b88bf5ba9ec82ed98f29e1bd27f455f957467e67
## 2 sha256:cb81cba87b88aa00c8acba3588fbe5034e74104c80499de8d329283744d688a6
## 3 sha256:3abc9f53d8d8672b195eb4d193f219efe10e8117892925d6cee49261dfe36c19
## 4 sha256:e588d8e35a243f20b5e775d31d86eebf4338bb5ca312f6e99625d16edd534ee5
## 5 sha256:3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353
## 6                                                               &lt;missing&gt;
##      created
## 1 1523909264
## 2 1523909264
## 3 1523909263
## 4 1523909263
## 5 1515532258
## 6 1515532258
##                                                                                                                created_by
## 1                                                                /bin/sh -c #(nop)  ENTRYPOINT ["/usr/local/bin/iterate"]
## 2                                                                        /bin/sh -c #(nop)  LABEL stevedore_version=0.0.1
## 3                                               /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "chmod +x /usr/local/bin/iterate"]
## 4 /bin/sh -c #(nop) COPY file:817b1679641b23eeaa7d56273e5ed5afba94d2effc1c32aea765ec2c77676730 in /usr/local/bin/iterate
## 5                                                                                      /bin/sh -c #(nop)  CMD ["/bin/sh"]
## 6                       /bin/sh -c #(nop) ADD file:093f0723fa46f6cdbd6f7bd146448bb70ecce54254c35701feeceb956414622f in /
##           tags    size comment
## 1 richfitz....       0
## 2                    0
## 3                    0
## 4                  306
## 5 alpine:l....       0
## 6              4147781</code></pre>
<p>(printing these objects is a real challenge!).</p>
<p>The <code>export()</code> method exports an image as a tar object. There is some work still required to make this work nicely (currently it returns a [potentially long] raw vector).</p>
<p>There are several methods that operate to modify or destroy the image:</p>
<p>The <code>$tag()</code> method will tag an image, for example</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">tag</span>(<span class="st">"richfitz/iterate"</span>, <span class="st">"0.0.1"</span>)
img$<span class="kw">reload</span>()
img$<span class="kw">tags</span>()</code></pre></div>
<pre><code>## [1] "richfitz/iterate:0.0.1"  "richfitz/iterate:latest"</code></pre>
<p>While the <code>$untag()</code> method will remove a tag</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">untag</span>(<span class="st">"richfitz/iterate:0.0.1"</span>)</code></pre></div>
<p>The <code>$remove()</code> method will remove an image - this returns a data.frame indicating what actually happened (images are only actually deleted if there are no other tags pointing at an image <em>and</em> if <code>noprune</code> is not <code>TRUE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">img$<span class="kw">remove</span>()</code></pre></div>
<pre><code>##                  untagged
## 1 richfitz/iterate:latest
## 2                    &lt;NA&gt;
## 3                    &lt;NA&gt;
## 4                    &lt;NA&gt;
## 5                    &lt;NA&gt;
## 6                    &lt;NA&gt;
##                                                                   deleted
## 1                                                                    &lt;NA&gt;
## 2 sha256:86f15ec2e15f7d505bb013d1b88bf5ba9ec82ed98f29e1bd27f455f957467e67
## 3 sha256:cb81cba87b88aa00c8acba3588fbe5034e74104c80499de8d329283744d688a6
## 4 sha256:3abc9f53d8d8672b195eb4d193f219efe10e8117892925d6cee49261dfe36c19
## 5 sha256:e588d8e35a243f20b5e775d31d86eebf4338bb5ca312f6e99625d16edd534ee5
## 6 sha256:b8c070c1be8e3298caa1c8a5f87f8b23bea72d7fe24f1a8837ba71ff5c1cf713</code></pre>
</div>
</div>
<div id="volumes" class="section level2">
<h2 class="hasAnchor">
<a href="#volumes" class="anchor"></a>Volumes</h2>
<p>Docker volumes provide a useful abstraction for interacting with (possibly persistent) file volumes across containers. To create a volume using <code>stevedore</code> (equivalent to <code>docker volume create</code>) use <code>$volume$create()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol &lt;-<span class="st"> </span>docker$volume$<span class="kw">create</span>(<span class="st">"myvolume"</span>)</code></pre></div>
<p>Volumes can be listed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$volume$<span class="kw">list</span>()</code></pre></div>
<pre><code>##                                                               name driver
## 1 32b935bb7b331482e45deb1be7ec0d57aaa1f6de1d4ad89049daa69f5e0ae0bf  local
## 2                                                         myvolume  local
##                                                                                       mountpoint
## 1 /var/lib/docker/volumes/32b935bb7b331482e45deb1be7ec0d57aaa1f6de1d4ad89049daa69f5e0ae0bf/_data
## 2                                                         /var/lib/docker/volumes/myvolume/_data
##   status labels scope options usage_data
## 1           bar local             NA, NA
## 2               local             NA, NA</code></pre>
<div id="working-with-volume-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-volume-objects" class="anchor"></a>Working with volume objects</h3>
<p>There’s very little that can be done with volume objets:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol</code></pre></div>
<pre><code>## &lt;docker_volume&gt;
##   help(help_type = getOption("help_type"))
##   inspect(reload = TRUE)
##   map(path, readonly = FALSE)
##   name()
##   reload()
##   remove(force = NULL)</code></pre>
<p>We can get the name:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol$<span class="kw">name</span>()</code></pre></div>
<pre><code>## [1] "myvolume"</code></pre>
<p>Inspect the metadata</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol$<span class="kw">inspect</span>()</code></pre></div>
<pre><code>## $name
## [1] "myvolume"
##
## $driver
## [1] "local"
##
## $mountpoint
## [1] "/var/lib/docker/volumes/myvolume/_data"
##
## $status
## NULL
##
## $labels
## NULL
##
## $scope
## [1] "local"
##
## $options
## NULL
##
## $usage_data
## NULL</code></pre>
<p>Generate mount definitions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol$<span class="kw">map</span>(<span class="st">"/comtainer/path"</span>)</code></pre></div>
<pre><code>## [1] "myvolume:/comtainer/path"</code></pre>
<p>and can remove the volume</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol$<span class="kw">remove</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<p>everything else comes from using volumes with containers.</p>
<p>Containers are mounted the same way as from the docker command line - with a string in the form <code>&lt;host&gt;:&lt;container&gt;</code>. Here we can use the volume name on the host side, so saying <code>&lt;myvolume&gt;:/myvolume</code> mounts our volume at <code>/myvolume</code> within the container. This can be done easily with the <code>$map()</code> method.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vol &lt;-<span class="st"> </span>docker$volume$<span class="kw">create</span>(<span class="st">"myvolume"</span>)
docker$container$<span class="kw">run</span>(
  <span class="st">"alpine:latest"</span>,
  <span class="kw">c</span>(<span class="st">"sh"</span>, <span class="st">"-c"</span>, <span class="st">"echo hello world &gt; /myvolume/output"</span>),
  <span class="dt">volumes =</span> vol$<span class="kw">map</span>(<span class="st">"/myvolume"</span>),
  <span class="dt">rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## &lt;docker_run_output&gt;
##   $container:
##     &lt;docker_container&gt;
##       id: a1b2fbf85fbc023b54990d4dc8de0cb6c3d7d5df20dde338ab4c3dec2d90c892
##       name: competent_albattani
##
##   $logs:
##</code></pre>
<p>(We use <code>sh -c</code> here so that the redirect operates within the container - the third argument is evaluated by the shell within the container and redirects the value that is echoed to a file.)</p>
<p>We can see the result of this by using a second container to read the file:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">run</span>(
  <span class="st">"alpine:latest"</span>,
  <span class="kw">c</span>(<span class="st">"cat"</span>, <span class="st">"/myvolume/output"</span>),
  <span class="dt">volumes =</span> vol$<span class="kw">map</span>(<span class="st">"/myvolume"</span>),
  <span class="dt">rm =</span> <span class="ot">TRUE</span>)$logs</code></pre></div>
<pre><code>## O&gt; hello world</code></pre>
<pre><code>## O&gt; hello world</code></pre>
</div>
</div>
<div id="networks" class="section level2">
<h2 class="hasAnchor">
<a href="#networks" class="anchor"></a>Networks</h2>
<p>Docker “networks” make it easy to get containers communicating with each other without exposing ports to the host. To achive this, one creates a docker network, then create containers attached to that network (containers can also be attached to networks after creation).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw &lt;-<span class="st"> </span>docker$network$<span class="kw">create</span>(<span class="st">"mynetwork"</span>)</code></pre></div>
<p>Networks can be listed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$network$<span class="kw">list</span>()</code></pre></div>
<pre><code>##              name
## 1 docker_gwbridge
## 2            host
## 3          bridge
## 4            none
## 5       mynetwork
##                                                                 id
## 1 5700a9c4d2908eea208cd9f5fe8c1a6d1864e51043ad73cc718b7eb2060ab4e9
## 2 2f80d37c9c534b35f1dfff0896f5391243432ad720dc6df371279dfb78fea0a3
## 3 676cc00e8893f7836dc7e8e4ecc06feb245b87200d9b3ac1ffa237f0148b380b
## 4 9bad2ae5c810c2d3fb9e2c73db5b733338189010b3e19803003051758a3962ba
## 5 959ce8cb240a2bcd6abca33f5fe4b1ea530de305d15f3bd76fb0e46a82d0bde2
##                          created scope driver enable_ipv6         ipam
## 1   2018-04-16T18:12:50.9705499Z local bridge       FALSE default,....
## 2           0001-01-01T00:00:00Z local   host       FALSE default,....
## 3 2018-04-15T21:28:23.685694069Z local bridge       FALSE default,....
## 4           0001-01-01T00:00:00Z local   null       FALSE default,....
## 5   2018-04-16T20:07:49.1996514Z local bridge       FALSE default,....
##   internal attachable ingress containers      options labels
## 1    FALSE      FALSE   FALSE            false, t....
## 2    FALSE      FALSE   FALSE
## 3    FALSE      FALSE   FALSE            true, tr....
## 4    FALSE      FALSE   FALSE
## 5    FALSE      FALSE   FALSE</code></pre>
<p>The networks <code>bridge</code>, <code>host</code> and <code>none</code> always exist - they are special to docker.</p>
<div id="working-with-network-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#working-with-network-objects" class="anchor"></a>Working with network objects</h3>
<p>Like volume objects, network objects do very little themselves:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw</code></pre></div>
<pre><code>## &lt;docker_network&gt;
##   connect(container = NULL, endpoint_config = NULL)
##   containers(reload = TRUE)
##   disconnect(container = NULL, force = NULL)
##   help(help_type = getOption("help_type"))
##   id()
##   inspect(reload = TRUE)
##   name(reload = TRUE)
##   reload()
##   remove()</code></pre>
<p>The <code>$name()</code> and <code>$id()</code> methods get the name and id of the network</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">name</span>()</code></pre></div>
<pre><code>## [1] "mynetwork"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">id</span>()</code></pre></div>
<pre><code>## [1] "959ce8cb240a2bcd6abca33f5fe4b1ea530de305d15f3bd76fb0e46a82d0bde2"</code></pre>
<p><code>$inspect()</code> gets detailed metadata</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">inspect</span>()</code></pre></div>
<pre><code>## $name
## [1] "mynetwork"
##
## $id
## [1] "959ce8cb240a2bcd6abca33f5fe4b1ea530de305d15f3bd76fb0e46a82d0bde2"
##
## $created
## [1] "2018-04-16T20:07:49.1996514Z"
##
## $scope
## [1] "local"
##
## $driver
## [1] "bridge"
##
## $enable_ipv6
## [1] FALSE
##
## $ipam
## $ipam$driver
## [1] "default"
##
## $ipam$config
## $ipam$config[[1]]
##          subnet         gateway
## "172.19.0.0/16"    "172.19.0.1"
##
##
## $ipam$options
## list()
##
##
## $internal
## [1] FALSE
##
## $attachable
## [1] FALSE
##
## $ingress
## [1] FALSE
##
## $containers
## list()
##
## $options
## character(0)
##
## $labels
## character(0)</code></pre>
<p><code>$containers()</code> lists containers attached to the network (currently an empty list - this network has no attached containers)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">containers</span>()</code></pre></div>
<pre><code>## list()</code></pre>
<p><code>$remove()</code> removes the network</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">remove</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<p>Generally you’ll want to put containers onto a network.</p>
<p>The setup here is to create a network, and then use the <code>network</code> argument to <code>$container$run()</code> to attach a container to that network. Once established, containers on the same network can use another docker container’s name as the hostname and communicate!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw &lt;-<span class="st"> </span>docker$network$<span class="kw">create</span>(<span class="st">"mynetwork"</span>)
server &lt;-<span class="st"> </span>docker$container$<span class="kw">run</span>(<span class="st">"nginx"</span>, <span class="dt">network =</span> nw, <span class="dt">name =</span> <span class="st">"server"</span>,
                               <span class="dt">detach =</span> <span class="ot">TRUE</span>, <span class="dt">rm =</span> <span class="ot">TRUE</span>)
server$<span class="kw">status</span>()</code></pre></div>
<pre><code>## [1] "running"</code></pre>
<p>Now we can attach other networks to this container and communicate with the server:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">run</span>(<span class="st">"alpine:latest"</span>, <span class="kw">c</span>(<span class="st">"ping"</span>, <span class="st">"server"</span>, <span class="st">"-c"</span>, <span class="st">"3"</span>),
                     <span class="dt">network =</span> nw, <span class="dt">stream =</span> <span class="kw">stdout</span>(), <span class="dt">rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## O&gt; PING server (172.19.0.2): 56 data bytes
## O&gt; 64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.146 ms
## O&gt; 64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.156 ms
## O&gt; 64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.212 ms
## O&gt;
## O&gt; --- server ping statistics ---
## O&gt; 3 packets transmitted, 3 packets received, 0% packet loss
## O&gt; round-trip min/avg/max = 0.146/0.171/0.212 ms</code></pre>
<pre><code>## &lt;docker_run_output&gt;
##   $container:
##     &lt;docker_container&gt;
##       id: 43c1a36a3f5f7f5dd6f64ea73bb8b5eafcb2ca8a26415d57a816b3d4e0f721d1
##       name: nostalgic_stallman
##
##   $logs:
##     O&gt; PING server (172.19.0.2): 56 data bytes
##     O&gt; 64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.146 ms
##     O&gt; 64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.156 ms
##     O&gt; 64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.212 ms
##     O&gt;
##     O&gt; --- server ping statistics ---
##     O&gt; 3 packets transmitted, 3 packets received, 0% packet loss
##     O&gt; round-trip min/avg/max = 0.146/0.171/0.212 ms</code></pre>
<p>Omitting the <code>network</code> argument, the second container can’t find the server:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$container$<span class="kw">run</span>(<span class="st">"alpine:latest"</span>, <span class="kw">c</span>(<span class="st">"ping"</span>, <span class="st">"server"</span>, <span class="st">"-c"</span>, <span class="st">"3"</span>),
                     <span class="dt">stream =</span> <span class="kw">stdout</span>(), <span class="dt">rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## E&gt; ping: bad address 'server'</code></pre>
<pre><code>## Error: Command 'ping server -c 3' in image 'alpine:latest' returned non-zero exit status 1
## ping: bad address 'server'</code></pre>
<p>The server container exposes a webserver on port 80. For containers on the network we can access this port:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">res &lt;-<span class="st"> </span>docker$container$<span class="kw">run</span>(<span class="st">"richfitz/curl"</span>, <span class="kw">c</span>(<span class="st">"curl"</span>, <span class="st">"-s"</span>, <span class="st">"http://server"</span>),
                            <span class="dt">network =</span> nw, <span class="dt">rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## O&gt; &lt;!DOCTYPE html&gt;
## O&gt; &lt;html&gt;
## O&gt; &lt;head&gt;
## O&gt; &lt;title&gt;Welcome to nginx!&lt;/title&gt;
## O&gt; &lt;style&gt;
## O&gt;     body {
## O&gt;         width: 35em;
## O&gt;         margin: 0 auto;
## O&gt;         font-family: Tahoma, Verdana, Arial, sans-serif;
## O&gt;     }
## O&gt; &lt;/style&gt;
## O&gt; &lt;/head&gt;
## O&gt; &lt;body&gt;
## O&gt; &lt;h1&gt;Welcome to nginx!&lt;/h1&gt;
## O&gt; &lt;p&gt;If you see this page, the nginx web server is successfully installed and
## O&gt; working. Further configuration is required.&lt;/p&gt;
## O&gt;
## O&gt; &lt;p&gt;For online documentation and support please refer to
## O&gt; &lt;a href="http://nginx.org/"&gt;nginx.org&lt;/a&gt;.&lt;br/&gt;
## O&gt; Commercial support is available at
## O&gt; &lt;a href="http://nginx.com/"&gt;nginx.com&lt;/a&gt;.&lt;/p&gt;
## O&gt;
## O&gt; &lt;p&gt;&lt;em&gt;Thank you for using nginx.&lt;/em&gt;&lt;/p&gt;
## O&gt; &lt;/body&gt;
## O&gt; &lt;/html&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(res$logs, <span class="dv">10</span>)</code></pre></div>
<pre><code>##  [1] "&lt;!DOCTYPE html&gt;\n"
##  [2] "&lt;html&gt;\n"
##  [3] "&lt;head&gt;\n"
##  [4] "&lt;title&gt;Welcome to nginx!&lt;/title&gt;\n"
##  [5] "&lt;style&gt;\n"
##  [6] "    body {\n"
##  [7] "        width: 35em;\n"
##  [8] "        margin: 0 auto;\n"
##  [9] "        font-family: Tahoma, Verdana, Arial, sans-serif;\n"
## [10] "    }\n"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">server$<span class="kw">stop</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nw$<span class="kw">remove</span>()</code></pre></div>
<pre><code>## NULL</code></pre>
</div>
</div>
<div id="other-docker-functions" class="section level2">
<h2 class="hasAnchor">
<a href="#other-docker-functions" class="anchor"></a>Other docker functions</h2>
<p>There are a few functions at the top level of the <code>docker_client</code> object:</p>
<p><code>$ping()</code> tests the connection to the server and reports the API version for the server - this is a (for docker) very fast function to use to test that things seem to be working.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$<span class="kw">ping</span>()</code></pre></div>
<pre><code>## [1] "OK"
## attr(,"api_version")
## [1] "1.37"
## attr(,"docker_experimental")
## [1] TRUE</code></pre>
<p><code>$api_version()</code> reports the API version that the <em>client</em> is using (this can be varied from 1.25 to 1.37)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$<span class="kw">api_version</span>()</code></pre></div>
<pre><code>## [1] "1.29"</code></pre>
<p><code>$version()</code> reports detailed version information from the server:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$<span class="kw">version</span>()</code></pre></div>
<pre><code>## $version
## [1] "18.04.0-ce"
##
## $api_version
## [1] "1.37"
##
## $min_api_version
## [1] "1.12"
##
## $git_commit
## [1] "3d479c0"
##
## $go_version
## [1] "go1.9.4"
##
## $os
## [1] "linux"
##
## $arch
## [1] "amd64"
##
## $kernel_version
## [1] "4.9.87-linuxkit-aufs"
##
## $experimental
## [1] TRUE
##
## $build_time
## [1] "2018-04-10T18:23:05.000000000+00:00"</code></pre>
<p><code>$info()</code> reports a bunch of other information about the state of the server (Docker describes this as “get system information” in its documentation) - this is equivalent to running <code>docker info</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">docker$<span class="kw">info</span>()</code></pre></div>
<pre><code>## $architecture
## [1] "x86_64"
##
## $containers
## [1] 1
##
## $containers_running
## [1] 0
##
## $containers_stopped
## [1] 1
##
## $containers_paused
## [1] 0
##
## $cpu_cfs_period
## [1] TRUE
##
## $cpu_cfs_quota
## [1] TRUE
##
## $debug
## [1] TRUE
##
## $discovery_backend
## [1] NA
##
## $docker_root_dir
## [1] "/var/lib/docker"
##
## $driver
## [1] "overlay2"
##
## $driver_status
## $driver_status[[1]]
## [1] "Backing Filesystem" "extfs"
##
## $driver_status[[2]]
## [1] "Supports d_type" "true"
##
## $driver_status[[3]]
## [1] "Native Overlay Diff" "true"
##
##
## $system_status
## list()
##
## $plugins
## $plugins$volume
## [1] "local"
##
## $plugins$network
## [1] "bridge"  "host"    "ipvlan"  "macvlan" "null"    "overlay"
##
##
## $experimental_build
## [1] TRUE
##
## $http_proxy
## [1] "gateway.docker.internal:3128"
##
## $https_proxy
## [1] "gateway.docker.internal:3129"
##
## $id
## [1] "X26Q:EYEC:M7AZ:IWRA:BTYD:ZJ4X:SJLK:OY4O:E376:4WMJ:ZEII:7AHU"
##
## $ipv4_forwarding
## [1] TRUE
##
## $images
## [1] 24
##
## $index_server_address
## [1] "https://index.docker.io/v1/"
##
## $init_path
## [1] NA
##
## $init_sha1
## [1] NA
##
## $kernel_version
## [1] "4.9.87-linuxkit-aufs"
##
## $labels
## character(0)
##
## $mem_total
## [1] 2096066560
##
## $memory_limit
## [1] TRUE
##
## $n_cpu
## [1] 2
##
## $n_events_listener
## [1] 2
##
## $n_fd
## [1] 25
##
## $n_goroutines
## [1] 42
##
## $name
## [1] "linuxkit-025000000001"
##
## $no_proxy
## [1] ""
##
## $oom_kill_disable
## [1] TRUE
##
## $os_type
## [1] "linux"
##
## $oom_score_adj
## [1] NA
##
## $operating_system
## [1] "Docker for Mac"
##
## $registry_config
## $registry_config$index_configs
## $registry_config$index_configs$docker.io
## $registry_config$index_configs$docker.io$mirrors
## character(0)
##
## $registry_config$index_configs$docker.io$name
## [1] "docker.io"
##
## $registry_config$index_configs$docker.io$official
## [1] TRUE
##
## $registry_config$index_configs$docker.io$secure
## [1] TRUE
##
##
##
## $registry_config$insecure_registry_cidrs
## [1] "127.0.0.0/8"
##
##
## $swap_limit
## [1] TRUE
##
## $system_time
## [1] "2018-04-16T20:07:56.7483986Z"
##
## $server_version
## [1] "18.04.0-ce"</code></pre>
<p>Finally, <code>$df()</code> will return information about resource and data usage by docker - all containers, networks, volumes, etc.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#containers">Containers</a></li>
      <li><a href="#images">Images</a></li>
      <li><a href="#volumes">Volumes</a></li>
      <li><a href="#networks">Networks</a></li>
      <li><a href="#other-docker-functions">Other docker functions</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Rich FitzJohn.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
